# Generated by Django 5.2 on 2025-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_expiry_date_productbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='has_barcode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_by_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
