# Generated by Django 5.2 on 2025-04-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_quantity_product_has_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockupdatelog',
            name='field_changed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockupdatelog',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockupdatelog',
            name='quantity_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockupdatelog',
            name='quantity_before',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
