# Generated by Django 5.2 on 2025-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockupdatelog_field_changed_stockupdatelog_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
