# Generated by Django 5.2 on 2025-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_losslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='is_expired_handled',
            field=models.BooleanField(default=False),
        ),
    ]
