# Generated by Django 5.2 on 2025-04-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_salesitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='losslog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Loss Log', 'verbose_name_plural': 'Loss Logs'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productbatch',
            options={'ordering': ['expiry_date'], 'verbose_name': 'Product Batch', 'verbose_name_plural': 'Product Batches'},
        ),
        migrations.AddField(
            model_name='productbatch',
            name='discount_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='discount_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='losslog',
            name='quantity_lost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
