# Generated by Django 5.2 on 2025-04-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='customer_name',
        ),
    ]
