# Generated by Django 5.2 on 2025-04-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_cashiershift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('refund', 'Refund')], default='cash', max_length=10),
        ),
    ]
