# Generated by Django 5.2 on 2025-04-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_salestransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='change_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
