# Generated by Django 5.2 on 2025-04-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
