# Generated by Django 5.2 on 2025-04-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_discountcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.discountcode'),
        ),
    ]
