# Generated by Django 5.2 on 2025-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_salestransaction_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_given', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spending_target', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
