# Generated by Django 5.2 on 2025-04-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_customerloyalty_loyaltysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='loyalty_discount_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
