# Generated by Django 5.2 on 2025-04-23 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_salestransaction_loyalty_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='loyalty_discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewarded_transactions', to='sales.discountcode'),
        ),
    ]
