# Generated by Django 5.2 on 2025-04-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_salestransaction_loyalty_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloyalty',
            name='rewards_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
