# Generated by Django 5.2 on 2025-04-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_customerloyalty_rewards_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='type',
            field=models.CharField(choices=[('staff', 'Staff'), ('loyalty', 'Loyalty')], default='staff', max_length=10),
        ),
    ]
